---
title: "R Notebook"
output: html_notebook
---

# libraries and load
```{r}
library(tidyverse)
library(tidytext)
library(lubridate)
library(ggthemes)
install.packages('digest')
library(digest)
library(showtext)
showtext_auto() 
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup")
library("ggmap")

cats_dogs <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-09-11/cats_vs_dogs.csv")
```

```{r}
glimpse(cats_dogs)

us <- c(left = -125, bottom = 25.75, right = -67, top = 49)
map <- get_stamenmap(us, zoom = 5, maptype = "toner-lite")
ggmap(map)

GOOGLE_MAPS_KEY
```

```{r}
cats_dogs %>%
  select(state, n_pet_households, n_cat_households, n_dog_households) %>%
  gather(species, value, 3:4) %>%
  filter(n_pet_households > 2000) %>%
  ggplot(aes(x=state, y=value, fill = species)) +
  geom_col(position = "fill")
```

```{r}
cats_dogs %>%
  select(state, n_pet_households, n_cat_households, n_dog_households) %>%
  gather(species, value, 3:4) %>%
  filter(n_pet_households > 2000) %>%
  group_by(state) %>%
  mutate(differences = value - lag(value)) %>%
  ggplot(aes(x=state,y=value, group = species)) +
    geom_col(aes(fill = species), position = "fill") +
    geom_text(aes(label = differences), na.rm = T, position = position_fill(1.1),family= "wqy-microhei", colour = "#f5f5f2") +
  geom_line(y=0.5, linetype = 2) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(labels = c("Cats", "Dogs"),values = c("#4E79A7","#E15759")) + 
  theme_light() +
  
  labs(x= "State", y = "% of Pets Per Household",
       colour = NULL,
       title = "OUR FRIENDS WITH PAWS",
       subtitle = "Dogs typically outnumber  cats in these larger states",
       caption = "@datajake | Source: American Veterinary Medical Association | #TidyTuesday") +
   theme(panel.border = element_blank(),
        text = element_text(colour = "gray20", family = "wqy-microhei"),
        axis.text.x = element_text(angle=25),
        axis.title.x = element_text(colour="grey20", face = "bold"),
        axis.title.y = element_text(colour="grey20", face = "italic"),
        plot.background = element_rect(fill = "#f5f5f2", color = NA),
        panel.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.background = element_rect(fill = "#f5f5f2", color = NA),
        plot.title = element_text(size=25, colour = "gray20", face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size=12, colour = "gray20", face = "italic", hjust = 0.5),
        plot.caption = element_text(size = 10, colour = "gray60", face = "italic"),
        plot.margin = margin(t=10, r=20, b=10, l=10, unit = "pt"))
```

```{r}
cats_dogs %>%
  select(state, n_pet_households, n_cat_households, n_dog_households) %>%
  gather(species, value, 3:4) %>%
  rename(Species = species) %>%
  filter(n_pet_households > 2000) %>%
  group_by(state) %>%
  mutate(check = paste0(round(value / n_pet_households ,2)*100, "%")) %>%
  ggplot(aes(x=state,y=value, group = Species), ) +
    geom_col(aes(fill = Species), position = "dodge") +
    geom_text(aes(label = check), na.rm = T, position = position_dodge(1), vjust = 1.5, family= "wqy-microhei") +
  scale_fill_manual(labels = c("Cats", "Dogs"),values = c("#4E79A7","#E15759")) + 
  theme_light() +
  
  labs(x= "State", y = "Total Pets",
       colour = NULL,
       title = "DOG/CAT DISPARITY PER HOUSEHOLD",
       subtitle = "Labels show percentage of species in pet households",
       caption = "@datajake | Source: American Veterinary Medical Association | #TidyTuesday") +
   theme(panel.border = element_blank(),
        text = element_text(colour = "gray20", family = "wqy-microhei"),
        axis.text.x = element_text(angle=25),
        axis.title.x = element_text(colour="grey20", face = "bold"),
        axis.title.y = element_text(colour="grey20", face = "italic"),
        plot.background = element_rect(fill = "#f5f5f2", color = NA),
        panel.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.background = element_rect(fill = "#f5f5f2", color = NA),
        plot.title = element_text(size=25, colour = "gray20", face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size=12, colour = "gray20", face = "italic", hjust = 0.5),
        plot.caption = element_text(size = 10, colour = "gray60", face = "italic"),
        plot.margin = margin(t=10, r=20, b=10, l=10, unit = "pt"))
```

```{r}

```

